In [28]:
import pandas as pd

#read the dataset
data = pd.read_csv("PBJ_Daily_Nurse_Staffing_Q2_2024.csv", encoding_errors="replace")
data.info(memory_usage='deep') #.head()

C:\Users\rob_m\AppData\Local\Temp\ipykernel_2832\3397973270.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("PBJ_Daily_Nurse_Staffing_Q2_2024.csv", encoding_errors="replace")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325324 entries, 0 to 1325323
Data columns (total 33 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   PROVNUM           1325324 non-null  object
 1   PROVNAME          1325324 non-null  object
 2   CITY              1325324 non-null  object
 3   STATE             1325324 non-null  object
 4   COUNTY_NAME       1325324 non-null  object
 5   COUNTY_FIPS       1325324 non-null  int64
 6   CY_Qtr            1325324 non-null  object
 7   WorkDate          1325324 non-null  int64
 8   MDScensus         1325324 non-null  int64
 9   Hrs_RNDON         1325324 non-null  float64
 10  Hrs_RNDON_emp     1325324 non-null  float64
 11  Hrs_RNDON_ctr     1325324 non-null  float64
 12  Hrs_RNadmin       1325324 non-null  float64
 13  Hrs_RNadmin_emp   1325324 non-null  float64
 14  Hrs_RNadmin_ctr   1325324 non-null  float64
 15  Hrs_RN            1325324 non-null  float64
 16  Hrs_RN_emp        1325324 non-null  float64
 17  Hrs_RN_ctr        1325324 non-null  float64
 18  Hrs_LPNadmin      1325324 non-null  float64
 19  Hrs_LPNadmin_emp  1325324 non-null  float64
 20  Hrs_LPNadmin_ctr  1325324 non-null  float64
 21  Hrs_LPN           1325324 non-null  float64
 22  Hrs_LPN_emp       1325324 non-null  float64
 23  Hrs_LPN_ctr       1325324 non-null  float64
 24  Hrs_CNA           1325324 non-null  float64
 25  Hrs_CNA_emp       1325324 non-null  float64
 26  Hrs_CNA_ctr       1325324 non-null  float64
 27  Hrs_NAtrn         1325324 non-null  float64
 28  Hrs_NAtrn_emp     1325324 non-null  float64
 29  Hrs_NAtrn_ctr     1325324 non-null  float64
 30  Hrs_MedAide       1325324 non-null  float64
 31  Hrs_MedAide_emp   1325324 non-null  float64
 32  Hrs_MedAide_ctr   1325324 non-null  float64
dtypes: float64(24), int64(3), object(6)
memory usage: 703.9 MB

In [29]:
data['WorkDate'] = pd.to_datetime(data['WorkDate'], format='ISO8601')#yearfirst=True)

# data1 = data.copy().loc[0:524287] #= data[]
# data1['PROVNUM'] = pd.to_numeric(data1['PROVNUM'])#data1['PROVNUM'].astype('int64')#
# data1['PROVNUM'].info()

In [3]:
data['WorkDate'].sample(10) #.sample(1)#

686163    2024-04-24
1320730   2024-05-18
489576    2024-06-27
97998     2024-06-22
758992    2024-05-23
120911    2024-06-03
260261    2024-04-02
41742     2024-06-04
1163448   2024-04-14
558676    2024-04-28
Name: WorkDate, dtype: datetime64[ns]

In [4]:
# data1[['PROVNUM', 'MDScensus']].info(memory_usage='deep')#[['PROVNUM', 'PROVNAME']]#
# check duplicate rows (result: none)
data.value_counts(['PROVNUM', 'WorkDate'])#sort=False)

PROVNUM  WorkDate
15009    2024-04-01    1
676124   2024-06-06    1
         2024-05-15    1
         2024-05-14    1
         2024-05-13    1
                      ..
265482   2024-04-17    1
         2024-04-16    1
         2024-04-15    1
         2024-04-14    1
555055   2024-04-19    1
Name: count, Length: 1325324, dtype: int64

In [6]:
from pandas.api.types import is_numeric_dtype

print("NUMERIC COLUMNS")
i=0
data_cols = data.iloc[:1].columns
for col in data_cols:
    numeric = is_numeric_dtype(data[col])
    if numeric:  #not 
        i+=1
        print(f"{i}: {col}")

NUMERIC COLUMNS
1: COUNTY_FIPS
2: MDScensus
3: Hrs_RNDON
4: Hrs_RNDON_emp
5: Hrs_RNDON_ctr
6: Hrs_RNadmin
7: Hrs_RNadmin_emp
8: Hrs_RNadmin_ctr
9: Hrs_RN
10: Hrs_RN_emp
11: Hrs_RN_ctr
12: Hrs_LPNadmin
13: Hrs_LPNadmin_emp
14: Hrs_LPNadmin_ctr
15: Hrs_LPN
16: Hrs_LPN_emp
17: Hrs_LPN_ctr
18: Hrs_CNA
19: Hrs_CNA_emp
20: Hrs_CNA_ctr
21: Hrs_NAtrn
22: Hrs_NAtrn_emp
23: Hrs_NAtrn_ctr
24: Hrs_MedAide
25: Hrs_MedAide_emp
26: Hrs_MedAide_ctr

In [37]:
# To check if all days are present in a Time Series
def check_missing_days(ts):
    import pandas as pd

    # Example time series
    # dates = pd.date_range("2023-01-01", "2023-01-10").delete([3, 7])  # missing Jan 4 and Jan 8
    # ts = pd.Series(range(len(dates)), index=dates)
    # ts.index.values[0]='2022-03-01'
    # ts[2]='2024-03-10'; ts[91]='2024-07-10'

    # Expected full range
    full_range = pd.date_range(ts.min(), ts.max(), freq="D")
    # full_range = pd.date_range(ts.index.min(), ts.index.max(), freq="D")

    # Check if all days are present
    missing_days = full_range.difference(ts)
    return missing_days

missing_days = check_missing_days(data.copy()['WorkDate'])
if len(missing_days) == 0:
    print("No missing date")
else:
    print(missing_days)

No missing date

In [ ]:
import numpy as np
# data.iloc[:1,9:]#.info()

# check total hrs against emp+ctr
# Hrs_RN = data[data['Hrs_RN_ctr']>0].iloc[:,15:18]
# Hrs_RN['Total'] = Hrs_RN['Hrs_RN_emp'] + Hrs_RN['Hrs_RN_ctr']
# Hrs_RN[~np.isclose(Hrs_RN['Hrs_RN'], Hrs_RN['Total'])][['Hrs_RN', 'Total']]

# Hrs_LPN = data[data['Hrs_LPN_ctr']>0].iloc[:,21:24]#
# Hrs_LPN['Total'] = Hrs_LPN['Hrs_LPN_emp'] + Hrs_LPN['Hrs_LPN_ctr']
# Hrs_LPN[~np.isclose(Hrs_LPN['Hrs_LPN'], Hrs_LPN['Total'])][['Hrs_LPN', 'Total']]

# Hrs_CNA = data[data['Hrs_CNA_ctr']>0].iloc[:,24:27]#
# Hrs_CNA['Total'] = Hrs_CNA['Hrs_CNA_emp'] + Hrs_CNA['Hrs_CNA_ctr']
# Hrs_CNA[~np.isclose(Hrs_CNA['Hrs_CNA'], Hrs_CNA['Total'])][['Hrs_CNA', 'Total']]

In [38]:
import numpy as np
# NurseHrs-to-Patient Ratio
data['NurseHrs'] = round(data['Hrs_RN'] + data['Hrs_LPN'] + data['Hrs_CNA'], 2)
data['NurseHrs-to-Patient Ratio'] = round(data['NurseHrs'] / data['MDScensus'], 2)
data[(data['NurseHrs-to-Patient Ratio']!=np.inf)&(data['NurseHrs-to-Patient Ratio'].notna())]\
[['PROVNUM', 'WorkDate', 'NurseHrs-to-Patient Ratio', 'NurseHrs', 'MDScensus']].sort_values('NurseHrs-to-Patient Ratio', ascending=False)#, na_position='first') #, 'Hrs_RN', 'Hrs_LPN', 'Hrs_CNA'

         PROVNUM   WorkDate  NurseHrs-to-Patient Ratio  NurseHrs  MDScensus
53542     045477 2024-05-05                     193.08    193.08          1
53540     045477 2024-05-03                     174.57    174.57          1
272144    145446 2024-05-25                     169.63  14079.00         83
53541     045477 2024-05-04                     154.04    154.04          1
736454  325214.0 2024-06-22                     138.42    138.42          1
...          ...        ...                        ...       ...        ...
921320    375174 2024-05-07                       0.00      0.00         51
549584    235352 2024-05-06                       0.00      0.00         74
921319    375174 2024-05-06                       0.00      0.00         50
549581    235352 2024-05-03                       0.00      0.00         77
549557    235352 2024-04-09                       0.00      0.00         73

[1325004 rows x 5 columns]

In [39]:
# Total Nurse Hours Per Hospital Per State Per Month
data['WorkMonth'] = data['WorkDate'].dt.to_period('M')#.astype(str)
# data[['WorkMonth', 'WorkDate']]
data.groupby(['PROVNUM', 'STATE', 'WorkMonth'])['NurseHrs'].sum()

# verify sum using filter
# data[(data['PROVNUM']==15012)&(data['STATE']=='AL')&(data['WorkMonth']=='2024-06')]['NurseHrs'].sum()

PROVNUM  STATE  WorkMonth
15009    AL     2024-04      6156.11
                2024-05      6351.22
                2024-06      6647.92
15010    AL     2024-04      9014.25
                2024-05      8919.00
                              ...
555053   CA     2024-06      5790.14
555054   CA     2024-04      4582.88
                2024-05      4933.29
                2024-06      4531.79
555055   CA     2024-04      4466.31
Name: NurseHrs, Length: 43727, dtype: float64

In [40]:
# understand reliance on temporary staff
data['NurseHrs_ctr'] = round(data['Hrs_RN_ctr'] + data['Hrs_LPN_ctr'] + data['Hrs_CNA_ctr'], 2)
data['NurseHrs_emp'] = round(data['Hrs_RN_emp'] + data['Hrs_LPN_emp'] + data['Hrs_CNA_emp'], 2)

data['NurseHrs_ctr Pct'] = round(data['NurseHrs_ctr'] / data['NurseHrs'] * 100, 2)
data['NurseHrs_emp Pct'] = round(data['NurseHrs_emp'] / data['NurseHrs'] * 100, 2)

# data[data['NurseHrs_ctr Pct'] > 50.0][['NurseHrs_ctr Pct', 'NurseHrs', 'NurseHrs_ctr', 'NurseHrs_emp']].sort_values('NurseHrs_ctr Pct', ascending=False) #
data[data['NurseHrs_ctr Pct'] > 50.0][['PROVNUM', 'WorkDate', 'NurseHrs_ctr Pct', 'NurseHrs_emp Pct']].sort_values('NurseHrs_ctr Pct', ascending=False) #

          PROVNUM   WorkDate  NurseHrs_ctr Pct  NurseHrs_emp Pct
722160   315396.0 2024-06-15            100.00              0.00
234732     115551 2024-05-14            100.00              0.00
234725     115551 2024-05-07            100.00              0.00
234726     115551 2024-05-08            100.00              0.00
234727     115551 2024-05-09            100.00              0.00
...           ...        ...               ...               ...
126243     065379 2024-04-27             50.01             49.99
686450     28E299 2024-05-08             50.01             49.99
1043890    435100 2024-04-30             50.01             49.99
1030324    425169 2024-04-23             50.01             49.99
380011     165320 2024-06-26             50.01             49.99

[24899 rows x 4 columns]

In [41]:
# Average number of patients per hospital
data.groupby(['PROVNUM'])['MDScensus'].mean().round(2).sort_values(ascending=False)

# Average number of patients per state
# data.groupby(['STATE'])['MDScensus'].mean().round(2)

# data.value_counts(['PROVNUM', 'WorkDate']).reset_index().query('count==1')

PROVNUM
335462    732.26
335100    683.18
335644    630.32
335136    551.35
335665    523.19
           ...
495167      3.31
205133      3.30
345542      3.19
335869      3.09
345512      1.42
Name: MDScensus, Length: 14600, dtype: float64

In [42]:
# Average number of patients per hospital per month
# data.value_counts(['PROVNUM', 'WorkMonth'])
data[data['PROVNUM']==335100].groupby(['PROVNUM', 'WorkMonth']).agg(AvgPatientCensus=('MDScensus', 'mean'),NumOfDays=('MDScensus','count')).reset_index()#['MDScensus'].mean().round(2)

   PROVNUM WorkMonth  AvgPatientCensus  NumOfDays
0   335100   2024-04        680.400000         30
1   335100   2024-05        688.387097         31
2   335100   2024-06        680.566667         30

In [43]:
# Hospitals with Highest Staffing Hours
data.groupby('PROVNUM')['NurseHrs'].sum().sort_values(ascending=False)

PROVNUM
335100      199144.72
335063      189810.35
335644      188650.15
335462      184704.83
335537      183568.98
              ...
495181          49.50
065187          49.00
225219.0        42.75
45401            0.00
315471.0         0.00
Name: NurseHrs, Length: 14600, dtype: float64

### Analytical Questions

In [44]:
# 1. What is the relationship between nurse staffing levels and patient census?
#    Among the nurse hours recorded, wherein the patient census is not zero,
#    the NurseHrs-to-Patient Ratio statistics are as follows:
#       mean value: 3.37 hrs/patient
#       min value:  0 hrs/patient
#       max value: 193.08 hrs/patient
data[(data['NurseHrs-to-Patient Ratio']!=np.inf)&(data['NurseHrs-to-Patient Ratio'].notna())]\
    [['WorkDate', 'NurseHrs-to-Patient Ratio', 'NurseHrs', 'MDScensus']].describe()
    # [['NurseHrs-to-Patient Ratio', 'NurseHrs', 'MDScensus']].sort_values('NurseHrs-to-Patient Ratio', ascending=False)
# data[(data['NurseHrs-to-Patient Ratio']>0.0)&(data['MDScensus']>0)]\
#     [['WorkDate', 'NurseHrs-to-Patient Ratio', 'NurseHrs', 'MDScensus']].describe()

,WorkDate,NurseHrs-to-Patient Ratio,NurseHrs,MDScensus
count,1325004,1.325004e+06,1.325004e+06,1.325004e+06
mean,2024-05-15 23:54:33.245966848,3.366523e+00,2.748254e+02,8.343685e+01
min,2024-04-01 00:00:00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2024-04-23 00:00:00,2.790000e+00,1.578100e+02,5.100000e+01
50%,2024-05-16 00:00:00,3.250000e+00,2.390550e+02,7.600000e+01
75%,2024-06-08 00:00:00,3.790000e+00,3.457300e+02,1.040000e+02
max,2024-06-30 00:00:00,1.930800e+02,1.407900e+04,7.420000e+02
std,NaN,1.103078e+00,1.771275e+02,4.902987e+01

In [45]:
# 2. Which hospitals have the highest staffing hours?
#    ISABELLA GERIATRIC CENTER INC at New York City has the highest staffing hours (NurseHrs).
#    Here's the top 10 list.
data.groupby(['PROVNUM','PROVNAME', 'CITY', 'STATE'])['NurseHrs'].sum().sort_values(ascending=False).head(10).reset_index()

,PROVNUM,PROVNAME,CITY,STATE,NurseHrs
0,335100,ISABELLA GERIATRIC CENTER INC,NEW YORK,NY,199144.72
1,335063,COLER REHABILITATION AND NURSING CARE CENTER,ROOSEVELT ISLAND,NY,189810.35
2,335644,KINGS HARBOR MULTICARE CENTER,BRONX,NY,188650.15
3,335462,THE PLAZA REHAB AND NURSING CENTER,BRONX,NY,184704.83
4,335537,"RUTLAND NURSING HOME, INC",BROOKLYN,NY,183568.98
5,395465,CEDARBROOK SENIOR CARE AND REHABILITATION,ALLENTOWN,PA,168048.55
6,335470,BORO PARK CENTER FOR REHABILITATION AND HEALTH...,BROOKLYN,NY,165315.25
7,335555,COLD SPRING HILLS CENTER FOR NURSING AND REHAB,WOODBURY,NY,163375.07
8,335136,LORETTO HEALTH AND REHABILITATION CENTER,SYRACUSE,NY,161609.35
9,335665,TERENCE CARDINAL COOKE HEALTH CARE CENTER,NEW YORK,NY,161061.96

In [46]:
# 3. What are the average staffing levels by state?
#    Here are the average staffing levels (NurseHrs) by state. NY tops the list.
data.groupby(['STATE'])['NurseHrs'].mean().round(2).sort_values(ascending=False)

STATE
NY    553.17
DC    465.41
NJ    386.26
FL    373.53
MD    352.54
CA    343.99
CT    335.08
PA    334.74
DE    332.04
HI    326.25
MA    321.23
AL    314.21
VA    306.91
RI    306.37
NV    304.41
SC    300.56
AZ    299.20
LA    296.37
MI    284.37
IL    273.84
WA    273.40
TN    272.35
NH    269.33
GA    266.67
MS    266.52
NC    263.58
AR    260.28
VT    259.83
KY    250.47
ND    248.32
AK    246.22
WV    243.02
OH    234.91
CO    233.01
ME    232.15
NM    227.88
OR    220.90
MN    207.43
IN    197.33
TX    196.32
WI    192.04
UT    189.37
MT    184.19
WY    180.90
MO    171.12
ID    170.02
NE    165.43
OK    164.39
IA    160.02
SD    158.37
KS    151.53
PR     88.93
Name: NurseHrs, dtype: float64

In [ ]:
# 4. Which facilities have the lowest nurse-to-patient coverage?
#    There are 108 facilities that have zero nurse-to-patient coverage between 1 to 91 days, with WHITE RIVER HEALTHCARE at CALICO ROCK, AR and ST CATHERINE OF SIENA at CALDWELL, NJ the worst.
data[(data['NurseHrs-to-Patient Ratio']!=np.inf)&(data['NurseHrs-to-Patient Ratio'].notna())&(np.isclose(data['NurseHrs-to-Patient Ratio'],0.0))]\
[['STATE', 'CITY', 'PROVNAME']].groupby(['STATE','CITY','PROVNAME']).size().reset_index(name='Number of Days').sort_values('Number of Days', ascending=False)

    STATE          CITY                         PROVNAME  Number of Days
0      AR   CALICO ROCK           WHITE RIVER HEALTHCARE              91
61     NJ      CALDWELL            ST CATHERINE OF SIENA              91
34     MA     WORCESTER       BEAR MOUNTAIN AT WORCESTER              87
9      CO          HUGO       LINCOLN HEALTH CARE CENTER              87
50     MS      COLUMBUS     BAPTIST MEMORIAL HOSPITAL GT              76
..    ...           ...                              ...             ...
68     NY         BRONX    BRONXCARE SPECIAL CARE CENTER               1
58     NE      HUMBOLDT      COLONIAL ACRES NURSING HOME               1
52     MT      BROWNING            BLACKFEET CARE CENTER               1
106    WV  CHARLES TOWN    WILLOW TREE HEALTHCARE CENTER               1
26     KY  MADISONVILLE  BRIGHTON CORNERSTONE GROUP, LLC               1

[108 rows x 4 columns]

In [69]:
# 5. Are certain states relying more on contract nurses?
#    Yes, 49 of the 52 states have relied more on contract nurses for 9 days at least, PA having the most days with 2544 days.
data[data['NurseHrs_ctr Pct'] > 50.0].groupby(['STATE'], as_index=False).size().sort_values('size', ascending=False)#['STATE'].size#
# data['STATE'].nunique()

   STATE  size
36    PA  2544
25    NC  1544
22    MO  1348
41    TX  1342
32    NY  1235
29    NJ  1230
8     GA  1134
21    MN   948
46    WI   855
33    OH   791
19    ME   765
27    NE   736
44    VT   672
4     CO   662
23    MS   631
10    IA   611
12    IL   535
26    ND   447
18    MD   436
17    MA   424
24    MT   408
39    SD   405
35    OR   392
14    KS   348
3     CA   348
47    WV   344
40    TN   305
15    KY   301
28    NH   286
38    SC   248
7     FL   234
43    VA   216
1     AR   214
13    IN   201
6     DE   177
20    MI   176
34    OK   171
16    LA   168
31    NV   166
45    WA   146
42    UT   144
11    ID   131
5     CT   128
30    NM   103
37    RI    86
48    WY    71
2     AZ    50
0     AK    33
9     HI     9

### codes below for testing only

In [ ]:
df = pd.DataFrame(
    {
        "first_name": ["John", "Anne", "John", "Beth"],
        "middle_name": ["A", "B", "A", "D"],
        "last_name": ["Smith", pd.NA, pd.NA, "Louise"]
    }
)
df

In [ ]:
import chardet

with open("PBJ_Daily_Nurse_Staffing_Q2_2024.csv", "rb") as f:
    raw = f.read()

result = chardet.detect(raw)
print(result)   # e.g. {'encoding': 'Windows-1252', 'confidence': 0.99}

# text = raw.decode(result["encoding"])

In [ ]:
# df.value_counts(['first_name', 'middle_name'])
df.value_counts()

In [67]:
data[data['PROVNUM']==235601.0][['STATE', 'CITY', 'PROVNAME', 'NurseHrs-to-Patient Ratio']]#[['PROVNUM']].info()#

       STATE        CITY                PROVNAME  NurseHrs-to-Patient Ratio
565565    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565566    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565567    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565568    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.20
565569    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.20
...      ...         ...                     ...                        ...
565651    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565652    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565653    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.00
565654    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.23
565655    MI  IRON RIVER  IRON RIVER CARE CENTER                       0.23

[91 rows x 4 columns]